nmcassa/letterboxdpy

- src/letterboxdpy/movie.py
- src/letterboxdpy/user.py
Hi! Great work so far with this scrapper. I was looking for a long time for one, and this one has almost every feature I needed. I added those two functions because I want to work with Diary data. Also added a movie_poster function.
New functions:
- User. user_diary_page: Retrieves all movies from a specific user's diary page.
- User. user_diary: Retrieves all movies from the user's diary.
- Movie.movie_poster: Acquires the link to the movie poster that was provided (movie_id).
> Functions that allow interaction with Letterboxd Diary and Posters

- pyproject.toml
- src/letterboxdpy/members.py
- src/letterboxdpy/movie.py
- src/letterboxdpy/user.py
Hey - made use of this project as a starting point for some scraping/parsing for a project I'm doing, so I thought I'd contribute back 😀. This just adds a couple features I wanted:
- parsing *all* film ratings for a user; more expansive than just diary entries. 
- grabbing a list of top N users for the site in the last year
> Add feature: member listings

- README.md
- letterboxdpy/avatar.py
- letterboxdpy/movie.py
- letterboxdpy/search.py
- letterboxdpy/user.py
> Documentation updates, fixes and new features

- README.md
- docs/movie/funcs/movie_details.md
- docs/movie/funcs/movie_watchers.md
- docs/user/funcs/user_activity.md
- docs/user/funcs/user_diary.md
- docs/user/funcs/user_films.md
- docs/user/funcs/user_followers.md
- docs/user/funcs/user_following.md
- docs/user/funcs/user_genre_info.md
- docs/user/funcs/user_lists.md
- docs/user/funcs/user_reviews.md
- docs/user/funcs/user_tags.md
- docs/user/funcs/user_watchlist.md
- docs/user/funcs/user_wrapped.md
- examples/exports/users/nmcassa/user.json
- letterboxdpy/decorators.py
- letterboxdpy/encoder.py
- letterboxdpy/films.py
- letterboxdpy/list.py
- letterboxdpy/members.py
- letterboxdpy/movie.py
- letterboxdpy/scraper.py
- letterboxdpy/search.py
- letterboxdpy/url.py
- letterboxdpy/user.py
- tests/test_movie.py
- tests/test_scraper.py
- tests/test_search.py
- tests/test_user.py
This pull request includes the following changes:
* **Created a test folder:** We can now test our classes using unittest.
* **Reduced some code duplication:** Our assert wrapper was made more flexible by taking an argument and was refactored to be called from a different file. An example of its usage was added to the same file.
* **Refactored user_films method:** The `user_films` method was refactored into an extractor to allow users to fetch their films in different ways. New functions were added that use this function.
* **Fixed some bugs and improved syntax:** Some bugs were fixed and the syntax was improved.
* **Moved JSON encoder to a separate file:** The JSON encoder we used in our classes was moved to a separate file (encoder.py) and called from there.
* **Enriched url.py:** The …
> Improvements

- README.md
- letterboxdpy/url.py
This PR:
- Adds docs for testing python scripts using built-in unittest
- Fixes missing f-string declarations in url.py
**Ignore previous commits listed in this PR, those were added to a separate branch and merged initially before being omitted in the current PR.
> Add docs for testing & f-string bugfix

- letterboxdpy/user.py
Extends user_following and user_followers to go through all pages.
Adds user_liked_reviews which returns a dict of all users whose reviews you've liked, a count of total reviews of theirs liked, and all the information needed to create links to each review (including multiple reviews of the same film)
> Update user.py - Extend followers/following, add user_liked_reviews

- letterboxdpy/user.py
- refactored functions
- new function
- code improvements
>  refactor: consolidate user_following and user_followers into user_network

- tests/test_user.py
- added new tests for user_followers and user_following functions in test_user.py.
- verified consistency between user statistics and fetched network data.
> feat(test_user): add tests for user followers and following

- docs/user/funcs/user_diary.md
- examples/export_user_diary_posters.py
- examples/exports/users/nmcassa/user_diary.json
- letterboxdpy/user.py
- letterboxdpy/utils/utils_parser.py
- added docstrings for clarity
- modularized code into helper functions:
- `retrieve_diary`
- `update_counters`
- `process_entry`
- `update_milestones`
- `update_watched_entries`
- fixed key mismatch in diary retrieval
- improved error handling and consistency
> refactor `user_wrapped` function

- letterboxdpy/user.py
- refactored `extract_user_films` to simplify movie extraction and reduce complexity.
- improved pagination logic by removing redundant loops and conditions.
- enhanced the calculation of liked and rating counts by using list comprehensions.
- improved readability and structure by refactoring code into helper functions (e.g., `get_movies_from_user_watched`).
- updated percentage calculations and ensured they handle edge cases (no ratings or likes).
> refactor(user): simplify `extract_user_films` logic and optimize pagination

- examples/exports/users/nmcassa/user_tags.json
- letterboxdpy/user.py
- **77fc97e**: fixed `user_wrapped` by adjusting internal functions and removing redundant parameters.
- **48c3946**: refactored `user_network` to use nested functions for page fetching and extraction.
- **7e4f82c**: modularized `extract_user_films` with nested functions.
- **ddebdf4**: restructured `user_lists` with nested functions.
- **7878913**: refactored `user_tags` function with nested functions.
> refactor: refactor user functions with nested functions

- examples/follow_stats.py
- letterboxdpy/utils/utils_terminal.py
- **feat:** added utility functions for terminal operations.
- **refactor:** improved the code structure of `follow_stats.py`:
- replaced manual installation prompt with `ImportError` raise for package issues.
- replaced `input` function with `get_input` utility for user input handling.
> refactor(follow_stats): improve error handling and refactor code structure

- examples/exports/users/nmcassa/user_activity.json
- letterboxdpy/user.py
- refactor user_activity to use nested functions  
- fix microsecond parsing in datetime  
- add total_logs key
> refactor: nested functions in user_activity and fix microsecond error

- examples/exports/users/nmcassa/user_activity.json
- letterboxdpy/user.py
- refactor `user_films_liked` to include `@assert_instance(User)` decorator
- add `@assert_instance(User)` decorator to `user_network` method
> refactor: update user methods and apply decorator

- examples/exports/users/nmcassa/user.json
- letterboxdpy/user.py
- enhanced `diary_recent` dictionary for better usability
- added movie slugs and organized entries by day index
> refactor: improve diary dictionary structure

- letterboxdpy/movie.py
- letterboxdpy/search.py
- letterboxdpy/user.py
- letterboxdpy/utils/utils_parser.py
- changed `print` statements in `movie.py` to use `json_dumps` for formatted JSON output
- added `extract_and_convert_shorthand` function to `utils/utils_parser.py` to handle shorthand notation (e.g., '6.3K')
- refactored code in various files to utilize the new shorthand conversion utility
> refactor: update print statements and add shorthand conversion utility

- docs/movie/funcs/movie_watchers.md
- letterboxdpy/constants/project.py
- letterboxdpy/movie.py
- letterboxdpy/search.py
- letterboxdpy/user.py
- letterboxdpy/utils/utils_parser.py
- letterboxdpy/utils/utils_transform.py
- refactored movie watchers statistics extraction for better performance and readability
- added project constants for ratings, genres, and month abbreviations
- added `month_to_index` and `index_to_month` utility functions for consistent month handling
- updated all month-related code to use the new utility functions
> refactor: improve movie watchers stats and update month utilities

- README.md
- docs/members/funcs/funcs/top_users.md
- docs/user/funcs/funcs/extract_user_films.md
- docs/user/funcs/funcs/user_films_liked.md
- docs/user/funcs/funcs/user_films_rated.md
- docs/user/funcs/funcs/user_network.md
- examples/export_user_data.py
- examples/exports/users/nmcassa/user_activity.json
- examples/exports/users/nmcassa/user_films_liked.json
- examples/exports/users/nmcassa/user_films_rated.json
- examples/exports/users/nmcassa/user_liked_reviews.json
- letterboxdpy/user.py
- remove duplicate documentation entries
- add new functions and update docs and examples
- fix invalid rating check in user films function
- simplify README.md and reflect current modules
> update docs and fix issues in user module

- examples/exports/users/nmcassa/user.json
- letterboxdpy/films.py
- letterboxdpy/list.py
- letterboxdpy/movie.py
- letterboxdpy/scraper.py
- letterboxdpy/search.py
- letterboxdpy/user.py
- feat(scraper): refactor scraper class to support class and instance methods
- refactor(user): replace instance methods with class methods for page fetching
- refactor(list): use class method for scraping
- refactor(search): change instance method call to class method for scraper
- refactor(films): change movie scraping to use class method for parser
- refactor(movie): use class method for parsing in movie class
- docs(user): update user data structure after using class method
- refactor(movie): replace hardcoded domain with constant
- refactor(user): replace hardcoded domain with constant from project settings
- refactor(list): use domain constant for urls
- refactor(search): replace domain constant with import from project constants
- refactor(list): reorganize import statements
- …
> refactor: use class methods and constants

- docs/check_docs.py
- letterboxdpy/avatar.py
- letterboxdpy/constants/project.py
- letterboxdpy/members.py
- letterboxdpy/utils/utils_parser.py
- feat(constants): add domain constant for base url
- refactor(members): reorder import statements
- refactor(members): update imports and refactor page fetching to use scraper class
- refactor(members): enhance members class and top_users function
- refactor(avatar): enhance avatar class with constants and improve error handling
- refactor(utils): add try_parse function for type conversion
- feat(docs): add list module to documentation check
> feat: enhance members and avatar classes, improve utils and docs

- letterboxdpy/constants/project.py
- letterboxdpy/core/decorators.py
- letterboxdpy/pages/user_profile.py
- letterboxdpy/pages/user_reviews.py
- pyproject.toml
- Updated project dependencies and configuration
- Added new URL protocols and domain constants
- Enhanced type hints and error handling
- Fixed user reviews scraping by updating to new Letterboxd DOM structure
- Improved film slug extraction in user profile
Fixes #67
> refactor: update project dependencies and DOM selectors

- letterboxdpy/pages/user_diary.py
Letterboxd HTML yapısı değiştiği için diary parsing'de KeyError oluşuyordu. 
Column selector'ları güncellendi (day→daydate, film→production, released→releaseyear) 
ve backward compatibility korundu.
Fixes diary functionality that was broken due to recent Letterboxd updates.
> fix: update user diary parser for Letterboxd HTML changes

- examples/follow_stats.py
- examples/user_plot_statistics.py
- examples/user_rating_plot.py
- letterboxdpy/constants/project.py
- letterboxdpy/pages/user_diary.py
- Convert scripts to classes:
- `FollowStatsAnalyzer`
- `LetterboxdRatingPlotter` 
- `LetterboxdStatisticsPlotter`
- Use centralized theming for all plots
- Add comprehensive statistics and better error handling
> refactor: modernize examples with class-based architecture

- letterboxdpy/pages/user_films.py
- letterboxdpy/pages/user_watchlist.py
- letterboxdpy/utils/movies_extractor.py
- Update movies_extractor.py to handle both old and new DOM structures
- Fix user_films.py to extract data from React components
- Fix user_watchlist.py to work with griditem containers
- Add nested functions with docstrings for better code readability
- Maintain backward compatibility with existing HTML structure
Resolves issue where get_watchlist() and get_films() returned empty results due to Letterboxd's migration to React-based components.
> Fix #87: Support Letterboxd's new React-based HTML structure

- docs/user/funcs/user_activity.md
- examples/exports/users/nmcassa/activity.json
- examples/exports/users/nmcassa/activity_following.json
- letterboxdpy/pages/user_activity.py
- Fix NameError: name 'username' is not defined in extract_activity()
- Refactor URL construction with cleaner base URL pattern
- Remove unnecessary username field from response data
Fixes #94
> Fix get_activity() NameError and improve URL construction - Issue #94

- docs/user/funcs/user_activity.md
- examples/exports/users/nmcassa/activity.json
- examples/exports/users/nmcassa/activity_following.json
- letterboxdpy/pages/user_activity.py
- letterboxdpy/utils/activity_extractor.py
- pyproject.toml
I have added an item slug for the user activity response since it was missing in the response and i needed it (to fetch the movie poster)
tests users are OK
> add item slug to user activity response

- docs/user/funcs/user_activity.md
- letterboxdpy/utils/activity_extractor.py
- I have fixed a little bug for the `review` entries, the rating was doubled.
The element look like this:
```html
<span class="rating -green rated-8"> ★★★★ </span>
```
and `get_rating()` took the integer from the class name so 8 but in reality it's 4, and i handle for floats too
- Add `rating` for basic review 
- Fix movie name for liked comment
- Fix doc
> fix: rating for entries

- letterboxdpy/list.py
- letterboxdpy/pages/user_list.py
- letterboxdpy/utils/utils_parser.py
Introduces functionality to extract the list ID from Letterboxd list pages and URLs. Updates List and ListMetaData classes to include the list_id attribute, adds extract_list_id and extract_list_id_from_url helper functions, and updates related methods and usage examples.
> feat: add list id extraction for user list

- letterboxdpy/search.py
Update parse_result method to handle new React component HTML structure.
Replace old data-film-slug with new data-item-slug attributes.
Tested with 30 films (100% success rate).
Fixes #129
> Fix search parsing error for new React component structure

- README.md
- examples/README.md
- examples/export_user_data.py
- examples/export_user_diary_posters.py
- examples/follow_stats.py
- examples/requirements.txt
- examples/search_and_export_lists.py
- examples/user_plot_statistics.py
- Add docstrings to all example scripts
- Simplify import statements
- Create examples/requirements.txt for dependencies
- Add examples/README.md with usage guide
- Update root README.md with examples section
> feat: improve examples with documentation and requirements
